#pragma once
#pragma pack(push,1)

// This code was automatically generated by the ApiGenerator plugin.
// Prefer updating the generator code instead of editing this directly.
// "u[]" variables are unknown data.

// Example entity: player
class CBaseMonster : public CBaseToggle {
public:
    byte u5_0[8];
    EHandle m_hEnemy; // the entity that the monster is fighting.
    EHandle m_hTargetEnt; // the entity that the monster is trying to reach.
    byte u5_1[8];
    EHandle m_hTargetTank; // Target tank to control.
    byte u5_2[80];
    float m_flFieldOfView; // width of monster's field of view ( dot product ).
    float m_flWaitFinished; // if we're told to wait, this is the time that the wait will be over.
    float m_flMoveWaitFinished; // if we're told to wait before moving, this is the time that the wait will be over.
    int m_Activity; // what the monster is doing (animation).
    int m_IdealActivity; // monster should switch to this activity.
    int m_GaitActivity; // gaitsequence.
    int m_LastHitGroup; // the last body region that took damage.
    int m_MonsterState; // monster's current state.
    int m_IdealMonsterState; // monster should change to this state.
    int m_iTaskStatus; // Task status.
    void* m_pSchedule; // Current schedule.
    void* m_pScheduleSaved; // For land_on_ground schedules (remember last schedule and continue).
    int m_iScheduleIndex; // Schedule index.
    byte u5_3[416];
    int m_movementGoal; // Goal that defines route.
    int m_iRouteIndex; // Index into m_Route[].
    float m_moveWaitTime; // How long I should wait for something to move.
    float m_moveradius; // Minimum radius.
    vec3_t m_vecMoveGoal; // Kept around for node graph moves, so we know our ultimate goal.
    int m_movementActivity; // When moving, set this activity.
    int m_iAudibleList; // first index of a linked list of sounds that the monster can hear.
    int m_afSoundTypes; // Sound types that can be heard.
    vec3_t m_vecLastPosition; // monster sometimes wants to return to where it started after an operation..
    int m_iHintNode; // this is the hint node that the monster is moving towards or performing active idle on..
    int m_afMemory; // Monster memory.
    int m_bloodColor; // color of blood particles.
    int m_iMaxHealth; // keeps track of monster's maximum health value (for re-healing, etc).
    vec3_t m_vecEnemyLKP; // last known position of enemy. (enemy's origin).
    int m_cAmmoLoaded; // how much ammo is in the weapon (used to trigger reload anim sequences).
    int m_afCapability; // tells us what a monster can/can't do.
    int m_afMoveShootCap; // tells us what a monster can/can't do, while moving.
    float m_flNextAttack; // cannot attack again until this time.
    int m_bitsDamageType; // what types of damage has monster (player) taken.
    byte u5_4[8];
    float m_lastDamageAmount; // how much damage did monster (player) last take.
    float m_tbdPrev; // Time-based damage timer.
    entvars_t* pevTimeBasedInflictor; // Time based damage inflictor.
    int m_failSchedule; // Schedule type to choose if current schedule fails.
    float m_flHungryTime; // Time based damage inflictor.
    float m_flDistTooFar; // if enemy farther away than this, bits_COND_ENEMY_TOOFAR set in CheckEnemy.
    float m_flDistLook; // distance monster sees (Default 2048).
    int m_iTriggerCondition; // for scripted AI, this is the condition that will cause the activation of the monster's TriggerTarget.
    string_t m_iszTriggerTarget; // Name of target that should be fired.
    vec3_t m_HackedGunPos; // HACK until we can query end of gun.
    byte u5_5[8];
    int m_scriptState; // internal cinematic state.
    EHandle m_hCine; // Cinematic entity.
    EHandle m_hCineBlocker; // Entity that is blocking cinematic execution.
    float m_useTime; // Don't allow +USE until this time.
    byte u5_6[48];
    string_t m_FormattedName; // The formatted name.<br>For better name outputs. E.g. "Alien Slave" rather than "alien_slave".
    byte u5_7[20];
    byte m_chTextureType; // Current texture type.<br>See TextureType enum.
    bool m_fCanFearCreatures; // Whether this monster can fear creatures.
    byte u5_8[26];
    float m_flAutomaticAttackTime; // How long an npc will attempt to fire full auto.
    float m_flFallVelocity; // Current fall speed.
    byte u5_9[16];
    EHandle m_hGuardEnt; // Monster will guard this entity and turn down follow requests.
    string_t m_iszGuardEntName; // Guard entity name.
    byte u5_10[84];
    vec3_t m_vecEffectGlowColor; // Glow shell.
    int m_iEffectBlockWeapons; // Monster can't use weapons.
    int m_iEffectInvulnerable; // is invulnerable (god mode)
    int m_iEffectInvisible; // is invisible (render + non-targetable)
    int m_iEffectNonSolid; // is non-solid
    float m_flEffectRespiration; // Extra/less breathing time underwater in seconds
    float m_flEffectGravity; // Gravity modifier (%)
    float m_flEffectFriction; // Movement friction modifier (%)
    float m_flEffectSpeed; // Movement speed modifier (%)
    float m_flEffectDamage; // Damage modifier (%)
};
#pragma pack(pop)
