#pragma once
#pragma pack(push,1)

// This code was automatically generated by the ApiGenerator plugin.
// Prefer updating the generator code instead of editing this directly.
// "u[]" variables are unknown data.

// Example entity: func_door
class CBaseToggle : public CBaseAnimating {
public:
    byte u3_0[2];
    int m_toggle_state; // Current toggle state.
    float m_flMoveDistance; // How far a door should slide or rotate.
    float m_flWait; // How long to wait before resetting.
    float m_flLip; // How much to stick out of a wall. Will recede further into walls if negative.
    float m_flTWidth; // For plats.
    float m_flTLength; // For plats.
    byte u3_1[4];
    vec3_t m_vecPosition1; // Closed position.
    vec3_t m_vecPosition2; // Open position.
    vec3_t m_vecAngle1; // Closed angle.
    vec3_t m_vecAngle2; // Open angle.
    int m_cTriggersLeft; // Trigger_counter only: # of activations remaining.
    float m_flHeight; // Height.
    EHandle m_hActivator; // Handle to the activator.
    byte u3_2[4];
    vec3_t m_vecFinalDest; // Final destination.
    vec3_t m_vecFinalAngle; // Final angle.
    int m_bitsDamageInflict; // DMG_ damage type that the door or trigger does.
    string_t m_sMaster; // This entity's master, if any.
};
#pragma pack(pop)
