#pragma once
#pragma pack(push,1)

// This code was automatically generated by the ApiGenerator plugin.
// Prefer updating the generator code instead of editing this directly.
// "u[]" variables are unknown data.

// Example entity: scripted_sequence
class CCineMonster : public CBaseMonster {
public:
    byte u7_0[12];
    string_t m_iszIdle; // Te idle animation name.
    string_t m_iszPlay; // The play animation name.
    string_t m_iszEntity; // The target entity name.
    byte u7_1[8];
    float m_flRadius; // The radius to search in.
    float m_flRepeat; // How much time has to pass before the scripted sequence can repeat.
    int m_iDelay; // Delay before execution.
    float m_startTime; // When to start the script.
    byte u7_2[12];
    bool m_interruptable; // Whether this scripted sequence can be interrupted.
    byte u7_3[3];
    float m_flMoveToRadius; // When in radius, script is done.
};
#pragma pack(pop)
