#pragma once
#pragma pack(push,1)

// This code was automatically generated by the ApiGenerator plugin.
// Prefer updating the generator code instead of editing this directly.
// "u[]" variables are unknown data.

// Example entity: path_track
class CPathTrack : public CBaseEntity {
public:
    byte u12_0[144];
    float m_length;
    string_t m_altName;
    float m_flNewSpeed; // New train speed
    float m_flMaxSpeed; // New maximum speed
    EHandle m_hNext;
    EHandle m_hPrevious;
    EHandle m_hAltpath;
};
#pragma pack(pop)
