// This code was automatically generated by the ApiGenerator plugin.

#include <extdll.h>
#include "EHandle.h"
#include "CBaseEntity.h"
#include "CBaseDelay.h"
#include "CBaseAnimating.h"
#include "CBaseToggle.h"
#include "CBaseButton.h"
#include "CBaseMonster.h"
#include "CBasePlayer.h"
#include "CCineMonster.h"
#include "CBasePlayerItem.h"
#include "CBasePlayerWeapon.h"
#include "CBaseTank.h"
#include "CItemInventory.h"
#include "CPathTrack.h"
#include "sc_enums.h"
